### ISSUE TITLE
Cannot use it with blogs hosted on wordpress.com

### ISSUE THREAD

**Issue by emanuelcds** [zachfeldman/rubypress#35]
Trying to use the gem with a free blog hosted at wordpress.com domain, I get an error for code 301 Moved Permanently. The same occurs for http code 302.

**Comment by seuros** [comment]
Probably the RPC api is not activated.

**Comment by emanuelcds** [comment]
Actually I identified the problem.
These blogs needs to run the XMLRPC requests over SSL and redirected automatically to the root when it's not.
