### ISSUE TITLE
Caching result

### ISSUE THREAD

**Issue by adaam2** [zachfeldman/rubypress#48]
How can I go about caching the result of `wp.getPosts`. My Wordpress Installation is hosted on a really slow server (Azure ergh) and loading in my most recent posts is affecting the speed of my lovely speedy Rails app! (Apologies, I'm a .NET dev)

**Comment by zachfeldman** [comment]
Hey there, this is not something the Gem does for you, you can do this on your side by storing posts in the database, redis, or just in a variable depending on your needs. If this is a feature you'd like to see though feel free to send a pull request and I'll consider it.
