### ISSUE TITLE
Error: 409:Duplicate comment detected; it looks as though you&#8217;ve already said that!

### ISSUE THREAD

**Issue by krunalinnovify** [zachfeldman/rubypress#50]
> When i use "wp.newComment" at that time i revived this error. Using "wp.newComment" comment is created but it does not gives response it's take time after some time it gives error. "Error: 409:Duplicate comment detected; it looks as though you&#8217;ve already said that!"

> My code snipped is like this.

> begin
      result = @wp.newComment(:blog_id => 0, # 0 unless using WP Multi-Site, then use the blog id
                      :username => UserName,
                      :password => Password,
                      :post_id => PostId,
                      :comment => {
                            :comment_parent => 0,
                            :content => content,
                            :author => AuthorName,
                            :author_url =>URL,
                            :author_email => AuthorEmail
                          }
                    )
      rescue XMLRPC::FaultException => e
        puts "Error: #{e.faultCode}:#{e.faultString}"
      end

> Give me Reply ASAP.
> 
> Thanks.

**Comment by zachfeldman** [comment]
Hey @krunalinnovify , this is not a support forum, it's an open source project that I maintain in my spare time. "Give me Reply ASAP" doesn't exactly make a good case for helping you.

It looks like this is a problem with WordPress, not RubyPress, so I'm closing this issue. Good luck!
