### ISSUE TITLE
Only fetching 10 post

### ISSUE THREAD

**Issue by anandshri** [zachfeldman/rubypress#53]
When I am calling getPosts method its only fetched 10 records.

**Comment by zachfeldman** [comment]
Yup, that is the WordPress default. https://codex.wordpress.org/Function_Reference/wp_get_recent_posts

This isn't a problem with this library so I'm closing this issue. Good luck with your project @anandshri !

**Comment by anandshri** [comment]
so it means this library only fetch 10 posts. is it not a bug of the library?
because obviously user wants to fetch all blogs through this library that was he expect from it.

**Comment by zachfeldman** [comment]
Nope it means that the underlying WordPress xml rpc library has a default of ten posts. This is a Ruby wrapper for that library. 

Please read the documentation, this isn't a WordPress support forum. I also do consulting for a fee, I can be reached via DM on Twitter.  Good luck with your project.
