### ISSUE TITLE
Since ruby 2.4.0 gem 'xmlrpc' needed

### ISSUE THREAD

**Issue by rimkashox** [zachfeldman/rubypress#54]
Just to signal that since ruby 2.4.0 we now need gem 'xmlrpc' to this work, maybe require it automatically ?

**Comment by zachfeldman** [comment]
Cool, I no longer use this gem actively in any projects so feel free to submit a pull request!

**Comment by rimkashox** [comment]
I tried adding `gem 'xmlrpc'` just after gemspec in the Gemfile https://github.com/rimkashox/rubypress/blob/master/Gemfile, but didn't work.. I still get the same error `active_support/dependencies.rb:293:in `require': cannot load such file -- xmlrpc/client (LoadError)`

But it does go away when I require directly the gem in my rails Gemfile...

Any idea ? I'm sure the solution is a one liner..

**Comment by zachfeldman** [comment]
Hey, are you sure you required the library after adding the gem/followed the instructions on the gem repo? https://github.com/ruby/xmlrpc

**Comment by rimkashox** [comment]
Hey Zach, yep this is required already by you in `rubypress.rb`, I just needed to add  `s.add_dependency 'xmlrpc'` to the gemspec file. Sending in a pull request now, I let you do the version change if necessary.

**Comment by zachfeldman** [comment]
New version pushed!

**Comment by zachfeldman** [comment]
Thanks again @rimkashox .

**Comment by mysticaltech** [comment]
My pleasure!
