### ISSUE TITLE
XMLRPC Issue

### ISSUE THREAD

**Issue by gnikoloudis** [zachfeldman/rubypress#56]
/usr/local/rvm/gems/ruby-2.3.0/gems/xmlrpc-0.3.0/lib/xmlrpc/client.rb:272:in `call': A name is required for this term. (XMLRPC::FaultException)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rubypress-1.2.2/lib/rubypress/client.rb:70:in `execute'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rubypress-1.2.2/lib/rubypress/posts.rb:29:in `newPost'
        from run_program.rb:56:in `post_to_wp'
        from run_program.rb:84:in `<main>'

I am getting the above error any suggestion?

**Comment by zachfeldman** [comment]
@gnikoloudis are you able to run the test suite locally? Can you tell us more about what parameters you're passing to the newPost method?
