### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by pacop** [zachfeldman/rubypress#7]
Hello, I am using this gem I am trying to upload media file, Obviously I am using uploadFile and my user in WordPress have permissions. I am using this code(get from spec)

```
wp.uploadFile(:data => {:id => "", :name => "test_file.png", :bits => '"\x89PNG\r\n\x1A\n\x00\x00\x00\rIHDR\x00\x00\x00\n\x00\x00\x00\n\b\x03\x00\x00\x00\xBA\xEC?\x8F\x00\x00\x00\x19tEXtSoftware\x00Adobe ImageReadyq\xC9e<\x00\x00\x00\fPLTE\xAC\xAC\xAC\x87\x87\x87aaa\xFF\xFF\xFF\xF2\xB3\r\x90\x00\x00\x00\x04tRNS\xFF\xFF\xFF\x00@*\xA9\xF4\x00\x00\x004IDATx\xDAl\x8D1\x12\x00 \f\xC2\x02\xFE\xFF\xCF\x82\x0Eu0\x03\x97r\xD7\x96U\xDC\xE0\x98;\xE1@\xDB$ \xA7\xACJ\x1F\xD5h\xD0]{\x8E\xCD\x8B-\xC0\x00/\x88\x00\xDF$\xC9\x85\\\x00\x00\x00\x00IEND\xAEB`\x82"'})
```

I have tried this also:

```
FILENAME = '/tmp/image.jpg'
f = File.new(FILENAME, 'rb').read
wp.uploadFile(:data => {:name => 'image.jpg',
                          :type => MIME::Types.type_for(FILENAME).first.to_s,
                          :bits => f
                          })
```

These images are uploaded but it is not valid images. How should I upload media?. Thanks

EDIT: I fix this, thanks and sorry

**Comment by T3RON** [comment]
hi @zachfeldman  im use this link [set featured image for WordPress post via XML-RPC](http://www.whatisthis.top/questions/1535300/set-featured-image-for-wordpress-post-via-xml-rpc) but i don't know what **img_id **

**Comment by zachfeldman** [comment]
Hey @T3RON I don't support this plugin for free but do occasionally do consulting around it - you can find me on Twitter under the same name. Otherwise you can file a new issue if you think there's something wrong with the gem itself.

**Comment by pacop** [comment]
You can read the whole doc here:
https://codex.wordpress.org/XML-RPC_WordPress_API/Media

Basically, it is the attachment id. You can get it from uploadFile (Return values of this function)

**Comment by T3RON** [comment]
Tank you for help
